### ISSUE TITLE
[REQ] time and percentage

### ISSUE THREAD

**Issue by cirelli94** [milliburn/gnome-shell-extension-battery_status#13]
Hi, thanks for your work for this extension.
Can you add an option for both time and percentage in display mode?
Thank you very much.

**Comment by skobkin** [comment]
Yeah. Please add this option. It would be very usable because under different workloads it's difficult to determine percentage by time and vice versa.

**Comment by RappelBerryPi** [comment]
My Suggestion is to install gnome tweaks and then navigate to 'Top Bar' and turn 'Battery Percentage' On. This will allow you to have the percentage on the top bar, and use this extension for the time.
![Screenshot from 2019-04-18 08-39-58](https://user-images.githubusercontent.com/35464495/56365026-94817e00-61b5-11e9-81f9-a26238b908c0.png)
