### ISSUE TITLE
Please update for 3.20

### ISSUE THREAD

**Issue by JanKoppe** [milliburn/gnome-shell-extension-battery_status#9]
This extension does not work with Gnome 3.20, which has been released for a few weeks. Please update it for 3.20!

**Comment by miguelcarax** [comment]
+1

**Comment by SalahAdDin** [comment]
:+1:

**Comment by SalahAdDin** [comment]
@milliburn What's about this man?

**Comment by real-artswan** [comment]
I've fixed it locally by editing the ~/.local/share/gnome-shell/extensions/battery_status@milliburn.github.com/metadata.json
Just add "3.20" to the "shell-version" array save and restart gnome-shell. It seems it works.

**Comment by JanKoppe** [comment]
This does not work for me. Won't display anything.

**Comment by noderat** [comment]
@JanKoppe My daily workflow was interrupted by broken extensions so I did PRs for a half a dozen extensions.

**Comment by roberth-k** [comment]
Thanks everybody for being persistent!

Optimistically merged #10; it's now been approved by [extensions.gnome.org](https://extensions.gnome.org). Please raise an issue if incompatibilities arise.
